# ProbeOps Frontend Docker Compose Configuration
# This file is specifically for deploying the frontend component
# To deploy: docker compose -f docker-compose.frontend.yml up -d

version: '3.8'

services:
  # Frontend React application service
  probeops-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      # Always rebuild from scratch to ensure proper file structure
      no_cache: true
    container_name: probeops-frontend
    ports:
      - "3000:3000"
    # Use production environment variables from .env.production file
    env_file:
      - .env.production
    restart: unless-stopped
    # Optional volume if you want to persist logs
    # volumes:
    #   - ./logs:/app/logs
    networks:
      - probeops-network

# Define networks to allow communication with the backend
networks:
  probeops-network:
    # Network name must match exactly what backend uses
    name: probeops-network
    # This is the critical flag - it tells Docker to use the existing network
    # instead of creating a new one with the same name
    external: true