# ProbeOps Frontend Docker Compose Configuration
# This file is specifically for deploying the frontend component
# To deploy: docker-compose -f docker-compose.frontend.yml up -d

version: '3.8'

services:
  # Frontend React application service
  probeops-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      # Always rebuild from scratch to ensure proper file structure
      no_cache: true
    container_name: probeops-frontend
    ports:
      - "3000:3000"
    environment:
      # Set this to the backend container name for Docker networking
      - VITE_API_URL=http://probeops-api:5000
      - PORT=3000
    restart: unless-stopped
    # Optional volume if you want to persist logs
    # volumes:
    #   - ./logs:/app/logs
    networks:
      - probeops-network

# Define networks to allow communication with the backend
networks:
  probeops-network:
    name: probeops-network
    # Using external: true allows this compose file to connect to the existing network
    # created by the backend docker-compose
    external: true