name: ProbeOps Frontend Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Run weekly on Sundays to keep dependencies up-to-date
  schedule:
    - cron: '0 0 * * 0'
  # Allow manual triggering
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Update browserslist DB
      run: npx update-browserslist-db@latest
      
    - name: Run ESLint
      run: npx eslint . --ext .ts,.tsx
      continue-on-error: true
    
    - name: Run TypeScript check
      run: npm run check
        
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run npm audit
      run: npm audit --audit-level=high
      continue-on-error: true
      
    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      id: dependency-check
      with:
        project: 'ProbeOps Frontend'
        path: '.'
        format: 'HTML'
        args: >
          --failOnCVSS 7
          --enableRetired
        
    - name: Upload dependency check report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: ${{ github.workspace }}/reports
        
  dependency-updates:
    name: Dependency Updates
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for outdated dependencies
      run: npm outdated || true
      
    - name: Check npm vulnerabilities
      run: npm audit || true